{% set version = '0.1.0' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-marquee
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/marquee_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/marquee/marquee_{{ version }}.tar.gz
  sha256: ef4b3798d1a85b0898eb03d8a8a4ecc3addebdceefacfb022c8ca37989b51994

build:
  merge_build_host: True  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ stdlib('c') }}          # [not win]
    - {{ compiler('m2w64_c') }}  # [win]
    - {{ stdlib('m2w64_c') }}    # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-cli
    - r-cpp11
    - r-glue
    - r-jpeg
    - r-png
    - r-rlang >=1.1.0
    - r-systemfonts >=1.1.0
    - r-textshaping >=0.4.0
    - r-vctrs
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-cli
    - r-cpp11
    - r-glue
    - r-jpeg
    - r-png
    - r-rlang >=1.1.0
    - r-systemfonts >=1.1.0
    - r-textshaping >=0.4.0
    - r-vctrs

test:
  commands:
    - $R -e "library('marquee')"           # [not win]
    - "\"%R%\" -e \"library('marquee')\""  # [win]

about:
  home: https://marquee.r-lib.org
  dev_url: https://github.com/r-lib/marquee
  license: MIT
  summary: Provides the mean to parse and render markdown text with grid along with facilities
    to define the styling of the text.
  license_family: MIT
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/MIT'
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - vitodelgrec

# Package: marquee
# Title: Markdown Parser and Renderer for R Graphics
# Version: 0.1.0
# Authors@R: c( person("Thomas Lin", "Pedersen", , "thomas.pedersen@posit.co", role = c("aut", "cre"), comment = c(ORCID = "0000-0002-5147-4711")), person("Martin", "Mitas", role = "aut", comment = "Author of MD4C"), person("Posit Software, PBC", role = c("cph", "fnd")) )
# Description: Provides the mean to parse and render markdown text with grid along with facilities to define the styling of the text.
# License: MIT + file LICENSE
# Encoding: UTF-8
# RoxygenNote: 7.3.1
# LinkingTo: cpp11
# Imports: cli, glue, grid, jpeg, png, rlang (>= 1.1.0), systemfonts (>= 1.1.0), textshaping (>= 0.4.0), utils, vctrs
# Suggests: ggplot2, gt, knitr, patchwork, ragg, rmarkdown, rsvg, testthat (>= 3.0.0)
# URL: https://marquee.r-lib.org, https://github.com/r-lib/marquee
# BugReports: https://github.com/r-lib/marquee/issues
# Config/Needs/website: tidyverse/tidytemplate
# VignetteBuilder: knitr
# Config/testthat/edition: 3
# NeedsCompilation: yes
# Packaged: 2024-05-28 06:35:19 UTC; thomas
# Author: Thomas Lin Pedersen [aut, cre] (<https://orcid.org/0000-0002-5147-4711>), Martin Mitas [aut] (Author of MD4C), Posit Software, PBC [cph, fnd]
# Maintainer: Thomas Lin Pedersen <thomas.pedersen@posit.co>
# Repository: CRAN
# Date/Publication: 2024-05-28 16:20:02 UTC
